### ISSUE TITLE
addViewToWindow() crashes with IllegalStateException

### ISSUE THREAD

**Issue by gmk57** [recruit-lifestyle/FloatingView#100]
In our project we show and hide FloatingView programmatically (it should only be shown when app is in background). Unfortunately, sometimes `FloatingViewManager.addViewToWindow()` crashes with

    java.lang.IllegalStateException: View jp.co.recruit_lifestyle.android.floatingview.FullscreenObserverView{3ed8eb3e V.ED.... ......ID 0,0-1,1134} has already been added to the window manager.
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:253)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
        at jp.co.recruit_lifestyle.android.floatingview.FloatingViewManager.addViewToWindow(FloatingViewManager.java:545)

Catching this exception results in duplicated FloatingView, so this may be the same issue as #99.
Version 2.3.2 did not have this issue, probably it was introduced while fixing #89.

Sample project: [FloatingViewTest.zip](https://github.com/recruit-lifestyle/FloatingView/files/2643823/FloatingViewTest.zip)
Issue is better reproduced with fast show/hide switching, but in real app I've seen a crash after >5 sec delay between hide and show.

We've tried some workarounds, but without success: recreating `FloatingViewManager` on each cycle produces duplicate FloatingViews sometimes, and `FloatingView.setVisibility(View.GONE)` often leaves it visible.

**Comment by YoshihideSogawa** [comment]
FloatingViewManager should be used within Service. It can not be used within Activity. For details, please read the [README](https://github.com/recruit-lifestyle/FloatingView).
Also, FloatingView is not designed to work according to Activity's lifecycle. If you want to use PIP (Picture In Picture), please use another library.

**Comment by gmk57** [comment]
Of course, in real project we use it in Service, and exactly the same crash happens there. Test project does not bother with services for the sake of simplicity. And we show FloatingView when/if app in NOT visible, so PIP is not an option. Please reopen.

**Comment by YoshihideSogawa** [comment]
I changed 'FloatingViewTest' to code that uses Service. It did not crash.
Also, when rewriting to this code, it did not crash.
```
        handler.post(new Runnable() {
            @Override
            public void run() {
                ImageView view = new ImageView(MainActivity.this);
                view.setImageResource(R.mipmap.ic_launcher);
                floatingViewManager.addViewToWindow(view, new FloatingViewManager.Options());
                if (!isFinishing()) {
                    handler.postDelayed(this, 3000L);
                }
            }
        });

        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                floatingViewManager.removeAllViewToWindow();
                if (!isFinishing()) {
                    handler.postDelayed(this, 3000L);
                }
            }
        }, 1000L);```

**Comment by gmk57** [comment]
In real project showing/hiding of FloatingView is controlled by observing `androidx.lifecycle.ProcessLifecycleOwner` inside Service. Sometimes user actions combined with other work in Android main thread results in lifecycle events delivered in quick succession. Specifically I suspect `addViewToWindow()` and immediately `removeAllViewToWindow()` produces abnormal state, so next call to `addViewToWindow()` (even after some delay) crashes.

This happens rarely (~20 crashes per week among 300 users). I reproduced it after many minutes of repeated quick switching between our app and home screen. So the purpose of my demo project was not to avoid crash, but to reproduce crash reliably. ;)

**Comment by geecko86** [comment]
Thank you for the insights, @gmk57!

Have you guys found a workaround? @YoshihideSogawa

**Comment by gmk57** [comment]
Given that v2.3.2 does not seem to have this issue, one possible solution is to replace checking for `ViewCompat.isAttachedToWindow()` in `FloatingViewManager.removeViewImmediate()` with simple try/catch. But this should be tested on device with Android 8 (where #89 is reproducible), and I don't have one at hand.

**Comment by geecko86** [comment]
@gmk57 I applied the change you suggested and tested the sample project you created (in the OP).

Not the cleanest fix, but it certainly seems to have fixed it the crashes! 🎉

It will have to do for now.

**Comment by YoshihideSogawa** [comment]
Please check on [Ver 2.4.1](https://github.com/recruit-lifestyle/FloatingView/releases/tag/2.4.1)

**Comment by gmk57** [comment]
Thank you very much! In test project v2.4.1 works fine, we'll try it in real life soon.
