### ISSUE TITLE
Laggy floatingview

### ISSUE THREAD

**Issue by mhackeras** [recruit-lifestyle/FloatingView#102]
Floatingview is sometimes laggy.  Other times works super smooth. And cant find any way to reproduce that will tell me why this happens. Isn't supposed to work smoothly all the time.?

**Comment by hannojg** [comment]
Take a look at my proposed merge request #115 
I bet it is because views are by default not hardware accelerated! 😄

**Comment by mhackeras** [comment]
@hannojg i saw you commited. did it work?

**Comment by hannojg** [comment]
Yes, otherwise I wouldn’t have committed it :) 
I had issues on low end devices, some of them even drawed just black views. 
With this small added flag everything works as expected (at least on my side).

**Comment by mhackeras** [comment]
@hannojg super nice bro good job!
I may download the project to check it.

**Comment by mhackeras** [comment]
@hannojg i should wait for the pull request to be accepted or i can try now ? dont really want to download the project.

**Comment by mhackeras** [comment]
It seems to be better :) ! will check more!

**Comment by hannojg** [comment]
Great to hear :)

**Comment by YoshihideSogawa** [comment]
Check [Ver 2.4.4](https://github.com/recruit-lifestyle/FloatingView/releases/tag/2.4.4)

**Comment by sureshappoets** [comment]
Floating icon is auto closed how to i fix that issue help me :)
