### ISSUE TITLE
Can't move view on some devices

### ISSUE THREAD

**Issue by HarryTylenol** [recruit-lifestyle/FloatingView#104]
I don't know why, My Pixel 3, Note 9 (Android Pie) works really well but view is not moving on some devices like Galaxy S8, Galaxy A8 2018 etc. 
Not also it can't be clicked but moving it. I already tested sample app on those devices but it was same.

**Comment by sucrow** [comment]
It is also reproduced in Note8(7.1.1) , Pixel 2(9.0)

**Comment by sucrow** [comment]
I found the cause of this problem. If you remove the animation scale, you cannot use this function. @HarryTylenol 개발자 옵션에서 애니메이션 배율 0으로 한거 아니신지 확인해보세요 ㅎㅎ

**Comment by HarryTylenol** [comment]
my animation scale setting was 0.5, but now I had replaced it with other overlay view. 
I'm curious animation scale setting was cuase of my issue.

@sucrow 0.5이긴 했는데, 이게 원인이었는지 어떤지 모르겠네요.
