### ISSUE TITLE
4.4.4 can`t show floating view

### ISSUE THREAD

**Issue by ljnalex** [recruit-lifestyle/FloatingView#11]
I run code on Android 5.0，FloatingView can show，but the version of Android later can`t show the floating view.

**Comment by YoshihideSogawa** [comment]
It worked correctly my device(Android 4.4.4 Nexus 5 Genymotion).
Did you change the code?

**Comment by ljnalex** [comment]
It works，I found the reason was the WindowManager.LayoutParams，thank you！
