### ISSUE TITLE
Back Button Functionality

### ISSUE THREAD

**Issue by kshitijcode** [recruit-lifestyle/FloatingView#13]
When I close the app , the chat head (Floating View ) disappears. Whats the issue ?

**Comment by YoshihideSogawa** [comment]
What's the "close" mean?(finish app? swipe the app history?)
Please show me sample code.

**Comment by kshitijcode** [comment]
Yes, on pressing back button, that is the app is finished the chathead goes odd and ondettachfromwindow()  is called.  But the same code works on Marshmallow.

**Comment by YoshihideSogawa** [comment]
What's the device and Android version?

**Comment by doodlleus** [comment]
Hi, I'm seeing the same issue. all the while the app is in memory the icon shows but if i swipe close the app from the recent apps view, the floating view icon also goes away until i reopen the app

**Comment by doodlleus** [comment]
just to add a bit: onTaskRemoved seems to get called and then sometimes, not all of the time, the view will reappear several seconds after and onStartCommand is called again

**Comment by doodlleus** [comment]
ok, i think i may have it. by default, the sample given returns START_REDELIVER_INTENT; on the onstartcommand. so im assuming that when the calling activity is closed the intent will try and start up again, sometimes successfully, sometimes not. If you want it to always reopen then change it to START_STICKY and if you want it to always stay closed change it to START_NOT_STICKY

**Comment by zeetherocker** [comment]
Are you sure its the back button ?
Because I had the issue only when I pressed back and moved to a game or the home screen (home being full screen)
I solved this by using setDisplayMode(DISPLAY_MODE_SHOW_ALWAYS) on my FloatingViewManager
