### ISSUE TITLE
How to open the FloatingView and show a custom layout in it?

### ISSUE THREAD

**Issue by HammadNasir** [recruit-lifestyle/FloatingView#15]
Upon clicking the FloatingView I want a custom layout to be displayed within itself and not as an intent.

How to do this?

Please let me know.

Thanks.

**Comment by HammadNasir** [comment]
are you there @YoshihideSogawa ?

**Comment by YoshihideSogawa** [comment]
FloatingView does not support complex layouts.
How about try using Activity of transparent background?

**Comment by HammadNasir** [comment]
thanks for replying.
can you suggest me some alternatives of your library? which supports what i want.
please.

**Comment by YoshihideSogawa** [comment]
Sorry, I don't know...

**Comment by zeetherocker** [comment]
@HammadNasir Check this out https://github.com/ericbhatti/floaties
Also for my project I was this library and I wanted to do the same thing, open a layout on click.
What I did was use another windowmanager to open my layout on click

`

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {

        if (mFloatingViewManager != null) {
            return START_STICKY;
        }

        final DisplayMetrics metrics = new DisplayMetrics();
        windowManager = (WindowManager) getSystemService(Context.WINDOW_SERVICE);
        windowManager.getDefaultDisplay().getMetrics(metrics);
        mChatHeadServiceBinder = new ChatHeadServiceBinder(this);
        final LayoutInflater inflater = LayoutInflater.from(this);
        final ImageView iconView = (ImageView) inflater.inflate(R.layout.widget_bubble, null, false);

        mFloatingViewManager = new FloatingViewManager(this, this);
        mFloatingViewManager.setFixedTrashIconImage(R.drawable.ic_trash_fixed);
        mFloatingViewManager.setActionTrashIconImage(R.drawable.ic_trash_action);
        final FloatingViewManager.Options options = new FloatingViewManager.Options();
        options.shape = FloatingViewManager.SHAPE_CIRCLE;
        options.overMargin = (int) (16 * metrics.density);
        mFloatingViewManager.addViewToWindow(iconView, options);

        LayoutInflater lay = LayoutInflater.from(this);
        //I added this Relative layout to control back press 
        relativeLayout = new RelativeLayout(this) {
            @Override
            public boolean dispatchKeyEvent(KeyEvent event) {
                if (event.getKeyCode() == KeyEvent.KEYCODE_BACK){
                    if(isShowing())
                        removeFloatingView();
                    return true;
                }
                return super.dispatchKeyEvent(event);
            }
        };

        RelativeLayout rel = (RelativeLayout) lay.inflate(R.layout.bubble_click_layout, null, false);
        //This is your layout
        final WebView webView = (WebView) rel.findViewById(R.id.webview);
        webView.loadUrl(asset);
        TextView text = (TextView) rel.findViewById(R.id.text);
        text.setText(name);
        params = new WindowManager.LayoutParams(
                WindowManager.LayoutParams.MATCH_PARENT,
                WindowManager.LayoutParams.WRAP_CONTENT,
                WindowManager.LayoutParams.TYPE_PHONE,
                WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL|WindowManager.LayoutParams.FLAG_WATCH_OUTSIDE_TOUCH,
                PixelFormat.TRANSLUCENT);

        params.gravity = Gravity.CENTER;
        params.x = 0;
        params.y = 0;
        params.windowAnimations = android.R.style.Animation_Dialog;

        relativeLayout.addView(rel);

        iconView.setOnClickListener(new View.OnClickListener() {
                                        @Override
                                        public void onClick(View v) {
                                            if (!showing) {
                                                addFloatingView();
                                            } else {
                                                removeFloatingView();
                                            }
                                        }
                                    }

        );

        return START_REDELIVER_INTENT;
    }`

**Comment by gnani185** [comment]
Hi can you post full code i don't understand @zeetherocker

**Comment by tmdler** [comment]
@YoshihideSogawa can you enable complex layouts in floatView?

**Comment by YoshihideSogawa** [comment]
No plans to support this feature.
Please refer to [this](https://github.com/recruit-lifestyle/FloatingView/issues/15#issuecomment-233894753).
