### ISSUE TITLE
Low res icons and trash_fix

### ISSUE THREAD

**Issue by sanved77** [recruit-lifestyle/FloatingView#16]
![screenshot_20160619-132647](https://cloud.githubusercontent.com/assets/9055612/16176101/3b0d3e3e-3622-11e6-8596-56392253d5d2.png)

![screenshot_20160619-133422](https://cloud.githubusercontent.com/assets/9055612/16176111/9cf077e2-3622-11e6-9f56-dae1addff174.png)

As you can see, the drag icon isn't high res. I tried putting a high res pic there but it just appears big in size. 
Even the trash icons aren't displayed correctly. Can you direct me how to fix this ?

**Comment by YoshihideSogawa** [comment]
FloatingView supports only a small image.

**Comment by sanved77** [comment]
Thanks for the follow up, however, the issue still persists. Even a low resolution file looks pretty distorted.

**Comment by YoshihideSogawa** [comment]
Support and fix [Ver 2.2](https://github.com/recruit-lifestyle/FloatingView/releases/tag/2.2)

**Comment by sanved77** [comment]
Thanks for fixing this.
