### ISSUE TITLE
floatview is killed when open game

### ISSUE THREAD

**Issue by quantqqq** [recruit-lifestyle/FloatingView#17]
floatview can display over native adroid app,
but when i open game, it get killed.
any way to solve that?

**Comment by zeetherocker** [comment]
I have the same issue. Any solutions yet ??

**Comment by zeetherocker** [comment]
I solved this issue! 
set the display mode.
use the setDisplayMode(DISPLAY_MODE_SHOW_ALWAYS) on your FloatingViewManager

Hope it solves the issue for you @quantqqq
