### ISSUE TITLE
How to remove view programmatically?

### ISSUE THREAD

**Issue by tmdler** [recruit-lifestyle/FloatingView#18]
Hi,
I search for method like removeView() to remove floating view from screen.
I found method mFloatingViewManager.removeAllViewToWindow() but seems its not working.

**Comment by YoshihideSogawa** [comment]
Please override FloatingViewListener and call stopSelf in "onFinishFloatingView" method.
(removeAllViewToWindow method call "onFinishFloatingView")
see [here](https://github.com/recruit-lifestyle/FloatingView/blob/master/sample/src/main/java/jp/co/recruit_lifestyle/sample/service/ChatHeadService.java#L109)
