### ISSUE TITLE
Float view moved when clickPressed

### ISSUE THREAD

**Issue by tmdler** [recruit-lifestyle/FloatingView#20]
When I press on float view it dragged.
How to disable it?

**Comment by YoshihideSogawa** [comment]
It does not support.
Please change [this value](https://github.com/recruit-lifestyle/FloatingView/blob/master/library/src/main/java/jp/co/recruit_lifestyle/android/floatingview/FloatingView.java#L54).

**Comment by YoshihideSogawa** [comment]
This request brings about major changes.
Moreover, I think that it doesn't need it ,so I will close this issue.
However, if there are many requests, I will implement it in the future.
