### ISSUE TITLE
 Unable to add window -- token null is not valid; is your activity running?

### ISSUE THREAD

**Issue by tmdler** [recruit-lifestyle/FloatingView#22]
I'm getting error:

```
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
at android.view.ViewRootImpl.setView(ViewRootImpl.java:562)
```

Error happens when i Pass applicationsContext instead of getActivity() into FloatingViewManager.
`mFloatingViewManager = new FloatingViewManager(getApplicationContext()
`

I have permission
`<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />`

in manifest but its not helps.

How to fix it?

**Comment by YoshihideSogawa** [comment]
Please send your android project.
