### ISSUE TITLE
Detect floatingview onmove

### ISSUE THREAD

**Issue by CoderProject** [recruit-lifestyle/FloatingView#23]
I need to remember the last position of the view. There is initial x and y options but how to detect view movement so i can save x and y.

**Comment by rachelfong** [comment]
Hi @CoderProject 

Did you manage to solve your issue?

**Comment by CoderProject** [comment]
see #29

**Comment by rachelfong** [comment]
Thank you for your reply. I managed to solve it with my own fork as well. Cheers.

**Comment by mhackeras** [comment]
guys how can you get in service.class the x and y from floating view ? :/

**Comment by YoshihideSogawa** [comment]
Supported in ver 2.1
Example 1: [ChatHeadService](https://github.com/recruit-lifestyle/FloatingView/blob/master/sample/src/main/java/jp/co/recruit_lifestyle/sample/service/ChatHeadService.java#L106)
Example 2: [CustomFloatingViewService](https://github.com/recruit-lifestyle/FloatingView/blob/master/sample/src/main/java/jp/co/recruit_lifestyle/sample/service/CustomFloatingViewService.java#L138)
