### ISSUE TITLE
Implement floatingView for Video streaming

### ISSUE THREAD

**Issue by AmirHadifar** [recruit-lifestyle/FloatingView#25]
Thanks for your awesome lib. I trying to play VideoView in **FloatingService** But it's buggy and when trying to show video screen goes to black (I think it's because of **SurfaceView** I'm not sure)

I also have another problem when I want to switch from current `VideoView` to your service I don't know how to continue from last position which is played. I Ask a question here But I didn't get answer could you please help me to solve this issue?

http://stackoverflow.com/questions/38615981/implement-floating-view-for-video-streaming

**Comment by YoshihideSogawa** [comment]
Did you try this way?
`mFloatingViewManager.setDisplayMode(FloatingViewManager.DISPLAY_MODE_SHOW_ALWAYS);`

I will try to solve the issue.

**Comment by AmirHadifar** [comment]
Thanks, I add `setDisplayMode` but unfortunately issue exist.

**Comment by YoshihideSogawa** [comment]
Sorry, this issue is outside the scope of this library warranty.
