### ISSUE TITLE
FloatingView not showing Android 4

### ISSUE THREAD

**Issue by thomprycejones** [recruit-lifestyle/FloatingView#27]
Hi, first of all, thank you!

I have a problem, i just realized that the floatingview i implemented on my app isn't showing on android 4 devices. And, searching for the problem, I tried the sample you gave us on an android 4 device and it isn't showing too.

I saw another closed issue where it was supposely working on android 4. Is there a workaround that i need to  implement for this?

**Comment by YoshihideSogawa** [comment]
This library works correctly on Android 4.1.1 Emulator.
1.Did you try it?
`mFloatingViewManager.setDisplayMode(FloatingViewManager.DISPLAY_MODE_SHOW_ALWAYS);`
2.Did you declare the service in AndroidManifest.xml?
3.What's device name and Android Version?

**Comment by thomprycejones** [comment]
The first option solved the issue, thanks!
