### ISSUE TITLE
permission denied for this window type. ..

### ISSUE THREAD

**Issue by Deeptimay** [recruit-lifestyle/FloatingView#35]
It worked fine on old phones. but on marshmallow and nougat it's crashing.
permission denied for this window type. .. on the line
`mFloatingViewManager.addViewToWindow(iconView, options);`

i guess this will do the job.
`params.type = WindowManager.LayoutParams.TYPE_TOAST;`

instead of 
`params.type = WindowManager.LayoutParams.TYPE_PRIORITY_PHONE;`

Please kindly update asap.. my app is crashing.

**Comment by YoshihideSogawa** [comment]
Do you write this permission in AndroidManifest?
`<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>`

You need to write runtime permissions.
see links
[Overlay Permission](https://github.com/recruit-lifestyle/FloatingView/blob/master/sample/src/main/java/jp/co/recruit_lifestyle/sample/fragment/FloatingViewControlFragment.java#L126)

[onActivityResult](https://github.com/recruit-lifestyle/FloatingView/blob/master/sample/src/main/java/jp/co/recruit_lifestyle/sample/fragment/FloatingViewControlFragment.java#L96)

**Comment by Deeptimay** [comment]
got it .. i need to add "runtime permissions".
Thanks.
