### ISSUE TITLE
Service starts, but nothing has been shown!

### ISSUE THREAD

**Issue by khaledkhj** [recruit-lifestyle/FloatingView#37]
Android version: 5.1.1
Device: Samsung Tablet A6

Any help please!

**Comment by YoshihideSogawa** [comment]
>Service starts
- Does the service describe in AndroidManifest?
- Describe it? `<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>`
- Did you write [it](https://github.com/recruit-lifestyle/FloatingView/blob/master/sample/src/main/java/jp/co/recruit_lifestyle/sample/service/ChatHeadService.java#L71) ?
- See #11
- See #35 
- See #27 
- Please try using the sample of FloatingView without changing it

If you can not solve it, please provide more detailed information

**Comment by khaledkhj** [comment]
Yeah, it is working fine now.
It was my fault, using app:srcCompat instead of just src, so that the service start but it did not show the image content.

Thanks anyway.

**Comment by YoshihideSogawa** [comment]
Maybe you seem to be using ImageView.
When using srcCompat, please use AppCompatImageView.
see [this](http://stackoverflow.com/questions/38221986/android-vector-drawable-appsrccompat-not-showing-images)

**Comment by AsadAlihp** [comment]
You are right, always use ```AppCompatImageView``` whenever you use ```app:srcCompat```

**Comment by AsadAlihp** [comment]
@YoshihideSogawa  I have been trying to attach floating menu buttons  with your beautiful bubble ```onClick listener``` . but failed . This [https://github.com/oguzbilgener/CircularFloatingActionMenu](url) is the library which I tried to use with Bubble. to reveal little bubbles around our Bubble.
