### ISSUE TITLE
How to make trash fixed icon smaller

### ISSUE THREAD

**Issue by VrtniPomidor** [recruit-lifestyle/FloatingView#38]
Just as title, how can i reduce the size of trash_fixed_icon. it is too large on my screen. I am setting a bitmap to the floating icon.

**Comment by YoshihideSogawa** [comment]
Please reduce the pixel size of the image.
This is the easiest way.

**Comment by VrtniPomidor** [comment]
Bitmap scaledBitmap= Bitmap.createScaledBitmap(bmp, 100, 100, false);
iconView.setImageBitmap(scaledBitmap);

mFloatingViewManager = new FloatingViewManager(this, this);
mFloatingViewManager.setFixedTrashIconImage(R.drawable.ic_trash_fixed);
mFloatingViewManager.setActionTrashIconImage(R.drawable.ic_trash_action);

the action one is good, it bounds the iconView well. the fixed one is still too large, can you notice my mistake from snippet? or you need more code?

**Comment by YoshihideSogawa** [comment]
I think that the pixel size of ic_trash_action is too large.
Please try one of the following.
- Edit ic_trash_action.png image to make it smaller
- Use the `FloatingViewManager.setActionTrashIconImage(Drawable)` method (you should convert the scaled Bitmap to Drawable)

**Comment by VrtniPomidor** [comment]
Yes the manual resize of the image resolved the issue, i thought they were sized based on the floating icon size, however is it possible you make it programatically possible (to resize trash icons)?

Thx for answer :)

**Comment by YoshihideSogawa** [comment]
The size of the action icon changes only when the Floating icon overlaps. The size of the fix icon does not change. It can not be changed programatically.
If you want to resize, please use only the action icon. (Include X mark in image)
