### ISSUE TITLE
How to make initial animation work

### ISSUE THREAD

**Issue by thisisPratzz** [recruit-lifestyle/FloatingView#41]
There is a option of initial animation, I tested it on miui and stock android it doesn't work

**Comment by YoshihideSogawa** [comment]
Thank you
It is a bug from Ver 2.2. ([This change](https://github.com/recruit-lifestyle/FloatingView/commit/47b4eddc68a7a17aac2da813caab31673de74aeb) seems to be a problem)
I will fix it at a later date.

**Comment by YoshihideSogawa** [comment]
Waiting for 2.2.2

**Comment by YoshihideSogawa** [comment]
Fixed [2.2.2](https://github.com/recruit-lifestyle/FloatingView/releases/tag/2.2.2)
