### ISSUE TITLE
Supporting for a complicated view

### ISSUE THREAD

**Issue by bqthuan** [recruit-lifestyle/FloatingView#5]
First of all, i'm sorry for posting here, i can't found your contact.
Can you make it supports a complicated view. I'm using the library, and my view has some buttons, the problem is i can't click on any button. Thanks in advanced.

**Comment by YoshihideSogawa** [comment]
Please show me a sample project.

**Comment by bqthuan** [comment]
@YoshihideSogawa I just investigated your source code, i think the library already support for interacting on child views, my project very complicated to show,so i'll create a new simple project to test again.

**Comment by bqthuan** [comment]
@YoshihideSogawa 
This is my code in the onStartCommand method of service

 LinearLayout layout = new LinearLayout(this);
        Button btn1 = new Button(this);
        btn1.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Log.e("Test", "onClick");
            }
        });
        btn1.setOnLongClickListener(new View.OnLongClickListener() {
            @Override
            public boolean onLongClick(View v) {
                Log.e("Test", "onLongClick");
                return true;
            }
        });
        btn1.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                Log.e("Test", "onTouch");
                return true;
            }
        });
        layout.addView(btn1);

        FloatingViewManager floatingViewManager = new FloatingViewManager(this, new FloatingViewListener() {
            @Override
            public void onFinishFloatingView() {

            }
        });
        floatingViewManager.setFixedTrashIconImage(R.mipmap.ic_launcher);
        floatingViewManager.setActionTrashIconImage(R.mipmap.ic_launcher);
        floatingViewManager.addViewToWindow(layout, new FloatingViewManager.Options());

Cannot interact with child view, add more child view is the same

**Comment by bqthuan** [comment]
@YoshihideSogawa 
And this problem, you can see yourself
![screenshot_2015-10-23-22-44-47 1](https://cloud.githubusercontent.com/assets/14837131/10697773/cb185f5c-79d7-11e5-94dd-305bf2b8325c.jpg)

**Comment by bqthuan** [comment]
@YoshihideSogawa are you there?

**Comment by YoshihideSogawa** [comment]
FloatingView is the View where there is a risk of compromising the UX.
So it will support only small and simple View.
If you want to achieve, please modify the following code.
https://github.com/recruit-lifestyle/FloatingView/blob/master/library/src/main/java/jp/co/recruit_lifestyle/android/floatingview/FloatingView.java#L459

Or use a transparent background Activity.
