### ISSUE TITLE
Bubble is Invisible 

### ISSUE THREAD

**Issue by AsadAlihp** [recruit-lifestyle/FloatingView#60]
Aright I did download the sample app and that is working fine, But when I add dependency of of FloatingView in my project everything is fine background service is running, I have add permission in manifest check it again and again but whenever I run the app click to button to show bubble but it never shows up mean while service gets started no error in log not at all. just can't see the bubble ...
awesome work btw...

**Comment by YoshihideSogawa** [comment]
Please check #37
