### ISSUE TITLE
FloatingView is to the right of the finger in landscape mode

### ISSUE THREAD

**Issue by geecko86** [recruit-lifestyle/FloatingView#68]
1. Rotate your phone to landscape so that the NavBar is on the left.
2. Make a "Simple FloatingView" appear in the FloatingView sample
3. Try to move it

The floatingview will not be under your finger. It is slightly to the right.

**Comment by geecko86** [comment]
I've reproduced this on Oreo and Nougat, on real devices and emulators, using the current branch. 1a715f6f125

**Comment by psmorandi** [comment]
Actually you don't even need to rotate, just create a Simple Floatview and it will be stucked. I reproduced your issue without rotate the device, just executed with new version (2.2.3) and I can't neither click nor drag/drop. When I have some time I will see if I can know what is really happening. For now just point back to 2.2.2 that is working.

**Comment by geecko86** [comment]
This is not the issue I described, then. It's not stuck, it's just 1cm to the right of my finger while I'm moving the FloatingView.

**Comment by YoshihideSogawa** [comment]
Fix [Ver 2.2.4](https://github.com/recruit-lifestyle/FloatingView/releases/tag/2.2.4)

**Comment by geecko86** [comment]
@YoshihideSogawa Sorry I'm late but the bug is still there in 2.2.4. You can see it in the in the sample.

Here you can see that the floatingView is not where my cursor is. It's about 72dp to the right of my cursor.

![left](https://i.imgur.com/hyX23K0.png)

This only happens when the navbar is on the left. This is what it looks like when the navbar is on the right.

![right](https://i.imgur.com/IWRUTvr.png)

**Comment by geecko86** [comment]
When I say cursor I just mean my finger.

**Comment by YoshihideSogawa** [comment]
Sorry for being late.
Support [Ver 2.3.0](https://github.com/recruit-lifestyle/FloatingView/releases/tag/2.3.0)
