### ISSUE TITLE
Support Android P

### ISSUE THREAD

**Issue by YoshihideSogawa** [recruit-lifestyle/FloatingView#82]
- [Foreground service permission](https://developer.android.com/about/versions/pie/android-9.0-changes-28#fg-svc)
- Test [rotation lock](https://developer.android.com/preview/behavior-changes.html#screen-rotation-changes)
- [DisplayCutout](https://developer.android.com/reference/android/view/DisplayCutout.html)  :weary:
    - Note:When use WindowManager.add () , DisplayCutout is null. That is, we must call getRootWindowInsets () from Fragment or Activity. :mask: :mask: :mask:
    - I want to get 'safe inset top' from Service...I don't know how...
        - [Suggest: More convenient to call the Cutout API](https://issuetracker.google.com/issues/79547510)
    - `mMetrics.heightPixels` does not include Cutout
- Cutout's Safe Area returns different values in portrait mode and landscape mode...

branch
https://github.com/recruit-lifestyle/FloatingView/tree/feature/support_p

**Comment by YoshihideSogawa** [comment]
Subtraction cutout `safeIInsetTop`.
https://github.com/recruit-lifestyle/FloatingView/blob/9d13cf3a990e6ecfd97be902673541ec1c0be60e/library/src/main/java/jp/co/recruit_lifestyle/android/floatingview/FloatingView.java#L1330

**Comment by harmoose** [comment]
@YoshihideSogawa when you mentioned Foreground service permission, do you mean just displaying a notification? Or is there a new permission added in P?

**Comment by YoshihideSogawa** [comment]
[2.4.0-alpha01](https://github.com/recruit-lifestyle/FloatingView/releases/tag/2.4.0-alpha01) has been released. Please check FloatingView on Android P.
Note:We do not recommend using this version in production.
