### ISSUE TITLE
Bugs on Galaxy S9+

### ISSUE THREAD

**Issue by nhatnd2009** [recruit-lifestyle/FloatingView#88]
When move floatingview, position between finger and the floatingview is wrong

**Comment by nhatnd2009** [comment]
![screenshot_1532879622](https://user-images.githubusercontent.com/22006664/43368187-b74758b6-9383-11e8-90c9-cd422e496a64.jpg)

**Comment by nhatnd2009** [comment]
i using newest version (2.3.2). Bug on Galaxy S9+, Nokia X6 ... (with 3 virtual button in screen, and in mode auto hide virtual button).

**Comment by YoshihideSogawa** [comment]
I am trying to fix this bug, but it is so difficult.
Note:Same issue
https://stackoverflow.com/questions/46107474/android-detect-samsung-galaxy-s8-navigation-bar-hide-or-show-programmatically

**Comment by YoshihideSogawa** [comment]
@nhatnd2009 
Please check [2.4.0-beta01](https://github.com/recruit-lifestyle/FloatingView/releases/tag/2.4.0-beta01)

**Comment by nhatnd2009** [comment]
thank you

Vào Th 6, 28 thg 9, 2018 vào lúc 18:55 Yoshihide Sogawa <
notifications@github.com> đã viết:

**Comment by nhatnd2009** [comment]
Hi, still bug
