### ISSUE TITLE
FloatingViewManager.removeAllViewToWindow() causes IllegalArgumentException

### ISSUE THREAD

**Issue by geecko86** [recruit-lifestyle/FloatingView#89]
I'm Here's the stacktrace.

> java.lang.IllegalArgumentException: View=jp.co.recruit_lifestyle.android.floatingview.a{2d7e2db VFE...C.. ......ID 0,0-216,216} not attached to window manager

> Caused By:
> android.view.WindowManagerGlobal.findViewLocked (WindowManagerGlobal.java:509)
> android.view.WindowManagerGlobal.removeView (WindowManagerGlobal.java:399)
> android.view.WindowManagerImpl.removeViewImmediate (WindowManagerImpl.java:123)
> **jp.co.recruit_lifestyle.android.floatingview.FloatingViewManager.removeAllViewToWindow (SourceFile:550)**
> **com.geecko.QuickLyric.services.LyricsOverlayService.onStartCommand (SourceFile:278)**
> android.app.ActivityThread.handleServiceArgs (ActivityThread.java:3639)
> android.app.ActivityThread.-wrap20 (Unknown Source)
> android.app.ActivityThread$H.handleMessage (ActivityThread.java:1768)
> android.os.Handler.dispatchMessage (Handler.java:108)
> android.os.Looper.loop (Looper.java:206)
> android.app.ActivityThread.main (ActivityThread.java:6749)
> java.lang.reflect.Method.invoke (Method.java)
> com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
> com.android.internal.os.ZygoteInit.main (ZygoteInit.java:845)

Have gotten several thousands crash reports like this in the past 30 days. 
The Library version that's used here is **2.3.1**.
Important to note it only happens with **Android 8**.

Perhaps you need to use [ViewCompat.isAttachedToWindow()](https://developer.android.com/reference/android/support/v4/view/ViewCompat.html#isAttachedToWindow(android.view.View))?

**Comment by dbof10** [comment]
I think adding `ViewCompat.isAttachedToWindow()` is also a bug too. My view is still there when the service is destroyed. I have to 

```
 val windowManager = getSystemService(WINDOW_SERVICE) as WindowManager
        try {
            windowManager.removeView(contextView!!.rootView)
        } catch (e: Exception) {
            Log.e(TAG, "Bubble remove view error " + e.message)
        }
```
