### ISSUE TITLE
Can't remove floating view

### ISSUE THREAD

**Issue by geecko86** [recruit-lifestyle/FloatingView#99]
On occasions, it appears to be possible to have duplicates floating views. Not sure if this is due to poor implementation on my end or because of this library.

What I do know is that only one of the floating views will be removable - which is definitely an issue with this library.

See [this example](https://gfycat.com/HonoredAnguishedAlligator).

Some users have reported this issue as well, sometimes to [extreme proportions](https://i.imgur.com/Mmaks4S.jpg). 

**These issues weren't present before v2.4.0.**

**Comment by dbof10** [comment]
same issue for me

**Comment by geecko86** [comment]
See this comment on another issue: 
https://github.com/recruit-lifestyle/FloatingView/issues/100#issuecomment-454239854

I can confirm the two issues are one and the same. Closing.

**Comment by dbof10** [comment]
Does it fix in 2.4.1?
